### ISSUE TITLE
Promise.reject() should take Error instead of string

### ISSUE THREAD

**Issue by kentonv** [nodecraft/acme-dns-01-cloudflare#11]
Hey, noticed another minor issue with ACME.js. I saw this in my log:

    Unhandled exception in Promise:  TypeError: Cannot create property 'action' on string 'No TXT records found for _acme-challenge.zero.kentonshouse.com'
        at /programs/server/npm/node_modules/@root/acme/acme.js:781:17
        at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

It looks like the string comes from here:

https://github.com/nodecraft/acme-dns-01-cloudflare/blob/a8e4d405d57121d65bf46fe2fca6d38c190a3adf/index.js#L104

The trouble is that this is throwing a bare string, but ACME.js expects errors to be of type `Error`. In particular it does this:

https://git.rootprojects.org/root/acme.js/src/branch/master/acme.js#L492-L497

    .catch(function(err) {
    	err.action = 'challenge_remove';
    	err.altname = ch.altname;
    	err.type = ch.type;
    	ACME._notify(me, noopts, 'error', err);
    });

So `err` at least has to be an object. I think it's normal convention to pass `Error` objects to `Promise.reject()`.

(You could also replace `return Promise.reject(...)` with `throw ...` which is equivalent in async functions and is a little bit less verbose.)

On another note, I am not sure why an error was being thrown in my case. The certificate was successfully issued and all DNS entries were successfully cleaned up so it seems like everything worked... so not sure what the error was about. :)

**Comment by Cherry** [comment]
Thanks, this is resolved in https://github.com/nodecraft/acme-dns-01-cloudflare/pull/12.

As for the error being thrown unexpectedly, I'm not too sure about that one. Was there perhaps multiple instances running which could have caused the records to been deleted by another running process? (Perhaps not checking for deleted records would just be the best solution...). If you've got a replictable test case though, I'd be happy to take a further look.

**Comment by kentonv** [comment]
There was only one certificate being requested. However, because we're requesting a wildcard certificate with both the wildcard and parent domain on SAN, this requires passing two challenges simultaneously. So two `_acme-challenge` records are created, and I believe `remove()` will be called twice to delete both of them. Could that cause the problem?

**Comment by Cherry** [comment]
That shouldn't cause any problems from my understanding. The two challenges for the single domain should be run in series, with one completing, and then the next one then starting. We do a similar thing where we request a cert for ~6 domains, for both the bare domain and wildcard for each, and haven't run into this issue yet. I'll see if I can replicate it on my end - let me know if it's something you're able to consistently replicate too.

**Comment by kentonv** [comment]
Hmm I was pretty sure I had observed ACME.js performing both challenges at once. At the very least, the test harness (`acme-dns-01-test`) does actually test running two challenges at once -- I had to account for that when writing my own plugin for sandcats.io, Sandstorm's optional dynamic DNS service.

When I get a chance I'll try it again and verify whether it runs the challenges simultaneously...

**Comment by Cherry** [comment]
Hmm, I never saw the DNS propagation waits in `acme-dns-01-test` happening simultaneously - it was always one after the other for each thing it was testing. It's very possible I'm misunderstanding that though.

I'll take another look on my end too, to see if I can replicate this. For some reason in my head, the DNS record deletion propagation being verified was to prevent the subsequent runs from having invalid data for that record, but I may be misremembering. 

Let me know if you can provide any more info - I really appreciate all of the feedback you've provided thus far.
