### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by alexcastillo** [nodecraft/acme-dns-01-cloudflare#13]
Hi there,

Thanks for this amazing project!

I'm running into this issue where I get `Response code 400 (Bad Request)` from Cloudflare. It does seem to work once in a while but I don't know why. 

```
(node:15786) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
HTTPError: Response code 400 (Bad Request) ErrorClass [HTTPError]: Response code 400 (Bad Request)
    at /node_modules/got/index.js:123:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'Response code 400 (Bad Request)',
  host: 'api.cloudflare.com',
  hostname: 'api.cloudflare.com',
  method: 'POST',
  path: '/client/v4/zones/***********************/dns_records',
  statusCode: 400,
  statusMessage: 'Bad Request',
  context: 'cert_issue',
  subject: 'test.example.com',
  altnames: [ 'test.example.com' ]
}
```

I'm also experiencing #7.

Any ideas?

**Comment by Cherry** [comment]
Hmm, this is an interesting one. If it's getting as far as calling `this.client.dnsRecords.add` to add a DNS record, the API token you're using must be generally working.

Can you confirm if you're using an API token, and if it has the applicable permissions to read all zones, and add/edit DNS records? I've also just pushed a new version which'll maintain a `cloudflare_errors` property on errors with API response errors from Cloudflare, which should make diagnosing issues like this much easier.

As for encountering #7, there's very little I can suggest here unfortunately other than the general DNS troubleshooting steps I suggested in that issue, and/or increasing the `waitFor` or `retries` options. Working with DNS for verification can be very flaky.

**Comment by alexcastillo** [comment]
Hey @Cherry,

Yes, I'm using an API token with all the applicable permissions. That being said, I just updated the token and the issue seems to have gone away. I hope it doesn't come back.

Do you have an example using the new `cloudflare_errors`?

Thanks!

**Comment by Cherry** [comment]
Interesting, thanks for the additional info. If it happens again, do let me know!

An example error with `cloudflare_errors` attached now just looks like this for example:
```
ErrorClass [HTTPError]: Response code 403 (Forbidden)
    at F:\GitHub\acme-dns-01-cloudflare\node_modules\got\index.js:123:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'Response code 403 (Forbidden)',
  host: 'api.cloudflare.com',
  hostname: 'api.cloudflare.com',
  method: 'GET',
  path: '/client/v4/zones?per_page=10&page=1',
  statusCode: 403,
  statusMessage: 'Forbidden',
  cloudflare_errors: [ { code: 9109, message: 'Invalid access token' } ]
}
```
Previously the raw response from Cloudflare was being lost, but is now retained for more easy debugging.

**Comment by alexcastillo** [comment]
Thanks, this is very useful!

**Comment by Cherry** [comment]
Sweet. I'll go ahead and close this for the time being as the issue appears to have been resolved. Feel free to reply or create a new issue if this issue persists, or you run into any other problems!
