### ISSUE TITLE
Error the "id" argument must be of a type String

### ISSUE THREAD

**Issue by zoutepopcorn** [nodecraft/acme-dns-01-cloudflare#20]
I had this code running before. Or I made a small change. I'm getting a strange error, I cant figure out what I'm doing wrong

**index.js**
```javascript
const Greenlock = require('greenlock');
const acmeDnsCloudflare = require('acme-dns-01-cloudflare');
const pkg = require('./package.json');

const TOKEN = "xxxx";
const EMAIL = "xxx@xxx"

const cloudflareDns01 = new acmeDnsCloudflare({
    token: TOKEN,
    verifyPropagation: true,
    verbose: true
});

console.log('dirname', __dirname);
const greenlock = Greenlock.create({
    staging: true,
    debug: true,
    maintainerEmail: EMAIL,
    packageRoot: "/home/xxx/cert_test",
    packageAgent: pkg.name + '/' + pkg.version,
    configDir: "/home/xxx/store",
    notify: function(event, details) {
        if ('error' === event) {
            // `details` is an error object in this case
            console.error(details);
        }
    }
});

greenlock.manager.defaults({
    agreeToTerms: true,
    subscriberEmail: EMAIL,
    packageRoot: __dirname,
    store: {
        module: "greenlock-store-fs",
        basePath: `/home/popcorn/WebstormProjects/webserver/cert_test/store/certs`
    },
    challenges: {
        "dns-01": cloudflareDns01
    }
});

greenlock.add({
    subject: "localh.app",
    altnames: ["localh.app", "*.localh.app"]
}).then(function(){
    console.log("SUCCESS");
}).catch(console.error);
```

Having an error:
```bash
Could not load 'undefined'
Did you install it?
        npm install --save undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:259:15)
    at validateString (node:internal/validators:123:11)
    at Module.require (node:internal/modules/cjs/loader:965:3)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.P._loadHelper (/home/xxx/cert_test/node_modules/@root/greenlock/plugins.js:29:32)
    at Object.P._loadChallenge (/home/popcorn/xxx/cert_test/node_modules/@root/greenlock/plugins.js:18:14)
    at /home/popcorn/xxx/cert_test/node_modules/@root/greenlock/greenlock.js:456:26
    at Array.map (<anonymous>)
    at Object.greenlock._order (/home/popcorn/xxx/cert_test/node_modules/@root/greenlock/greenlock.js:455:41)
    at async Object.greenlock._renew (/home/popcorn/xxx/cert_test/node_modules/@root/greenlock/greenlock.js:335:9) {
```

**Comment by Cherry** [comment]
Thanks for the report. I'm unable to replicate this myself in any of our projects, but looking at the code at https://git.rootprojects.org/root/greenlock.js/src/branch/master/plugins.js#L12-L26, seems to indicate that `P_loadHelper` is somehow being passed `undefined`. 

https://git.rootprojects.org/root/greenlock.js/issues/35 seems to be a related issue. Try tweaking the `packageRoot`, `configDir`, `store.basePath`, etc. directories - I expect it's related to that.

**Comment by ajuanjojjj** [comment]
I'm able to replicate it, using "acme-dns-01-cloudflare": "^1.2.3" and "greenlock": "^4.0.4". However, the "The "id" argument must be of type string. Received undefined" is not the end of the story, but just the error on the first run. 

Deleting the config folder causes it to happen again, but if the error is thrown and then node ran again, it'll throw 
`
Fatal error during greenlock init:
bad challenge dns-01 module config{"options":{"token":"\\hidden\\","verifyPropagation":true,"verbose":true},"client":{},"propagationDelay":0}
`

Server.js content:
`
const acmeDnsCloudflare = require("acme-dns-01-cloudflare");

const cloudflareDns01 = new acmeDnsCloudflare({
	token: "\\HIDDEN\\",
	verifyPropagation: true,
	verbose: true // log propagation delays and other debug information
});


const Greenlock = require("greenlock");
const pkg = require("./package.json");

const greenlock = Greenlock.create({
	packageAgent: pkg.name + "/" + pkg.version,
	configDir: "./store",
	packageRoot: __dirname,
	maintainerEmail: "ajuanjojjj@gmail.com"
});

greenlock.manager.defaults({
	agreeToTerms: true,
	subscriberEmail: "ajuanjojjj@gmail.com",
	store: {
		module: "greenlock-store-fs",
		basePath: "./store/certs"
	},
	challenges: {
		"dns-01": cloudflareDns01
	}
});

greenlock.add({
	"subject": "\\HIDDEN\\",
	"altnames": [
		"\\HIDDEN\\",
		"\\HIDDEN\\"
	]
}).then(function () {
	console.log("SUCCESS");
}).catch(console.error);
`

**Comment by ajuanjojjj** [comment]
Oh, and better not to abuse the tests, since you might hit the rate limit for your IP: https://letsencrypt.org/docs/rate-limits/

Guess how I found out (:

**Comment by ajuanjojjj** [comment]
After quite the evening of debugging, I think ive found where some of the (multiple) issues fall, although i'm not familiar with how the module works, so feel free to correct me where i'm wrong
index.js:57: 
- Missing a `this.module = "acme-dns-01-cloudflare";` declaration 
- The `cloudflare` class is not being saved correctly in the config.json file (JSON.stringify or something like that failing). Fixed by refactoring `this.client` to `this.cloudflareClient` and adding an extra `this.client` without the `cloudflare` prototype.
- The `client` data may be fed via `options.token` (server.js) or `options.client?.token` (config.json), so you have to check for both


Doing all of this seems to have fixed the issue, although more testing would be nice (I'm not completly sure i've not bypassed any extra errors while debugging)

**Comment by farzeni** [comment]
Same problem here @ajuanjojjj , do you have a public repo to check your changes?

**Comment by ajuanjojjj** [comment]
> Same problem here @ajuanjojjj , do you have a public repo to check your changes?

Just pushed a PR that fixed it for me, feel free to check it out :D

**Comment by farzeni** [comment]
Thank you @ajuanjojjj, it fixed the issue in my case

**Comment by zoutepopcorn** [comment]
Wow, that worked @ajuanjojjj great work 

I just copy / paste the node_modules/index.js with this content:
https://github.com/ajuanjojjj/acme-dns-01-cloudflare/blob/master/index.js. 

@Cherry can we accept this please

**Comment by ajuanjojjj** [comment]
> Wow, that worked @ajuanjojjj great work
> 
> I just copy / paste the node_modules/index.js with this content:
> https://github.com/ajuanjojjj/acme-dns-01-cloudflare/blob/master/index.js.
> 
> @Cherry can we accept this please

The PR is already linked, we just need to fix some minor stuff and it will be added on the next release!

(Also, if you find the module useful, please star it so it gets more traction and hopefully more people help tweaking/fixing it :D)

**Comment by Cherry** [comment]
Thanks for all the feedback and research here folks. An updated version (`1.2.4`) has been published with the PR from @ajuanjojjj which should resolve this issue. 🎉
