### ISSUE TITLE
[Bug ?] doesn't seem to ever be able to perform domain validation

### ISSUE THREAD

**Issue by Unyxos** [nodecraft/acme-dns-01-cloudflare#7]
Hi, I've been trying to generate let's encrypt certs using Greenlock v4 with cloudflare DNS challenge but it doesn't seem to ever be able to perform any form of verification.

I'm using node v12.14.1

I'm using a very basic setup for testing purposes : 

```javascript
'use strict';

var pkg = require('./package.json');
var Greenlock = require('greenlock');
var greenlock = Greenlock.create({
    packageRoot: __dirname,
    configDir: __dirname,
    packageAgent: pkg.name + '/' + pkg.version,
    maintainerEmail: "<my email address>",
    staging: true,
    notify: function(event, details) {
        if ('error' === event) {
            // `details` is an error object in this case
            console.error(details);
        }
    }
});

greenlock.manager.defaults({
    // The "Let's Encrypt Subscriber" (often the same as the maintainer)
    // NOT the end customer (except where that is also the maintainer)
    subscriberEmail: '<my email address>',
    agreeToTerms: true,
    store: {
        module: "greenlock-store-fs",
        basePath: "./store/certs"
    },
    challenges: {
        "dns-01": {
            module: "acme-dns-01-cloudflare",
            email: "<my cloudflare email address>",
            key: "<my global api key>"
        }
    }
});

greenlock.add({
    subject: "<my domain>",
    altnames: ["<my domain>"]
});
```

I'm getting the following output:

```
Error: DNS record deletion not yet propagated for _greenlock-dryrun-16ba4f41.<my domain>
    at Function.verifyPropagation (/c/Users/coren/PhpstormProjects/greenlocktest/node_modules/acme-dns-01-cloudflare/index.js:173:13)
    at async /c/Users/coren/PhpstormProjects/greenlocktest/node_modules/acme-dns-01-cloudflare/index.js:103:5
Waiting for 10000 ms before attempting propagation verification retry 1 / 30.
Error: queryTxt ENOTFOUND _acme-challenge.<my domain>
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryTxt',
  hostname: '_acme-challenge.<my domain>',
  context: 'cert_issue',
  subject: '<my domain>',
  altnames: [ '<my domain>' ]
}
Error: queryTxt ENOTFOUND _acme-challenge.<my domain>
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryTxt',
  hostname: '_acme-challenge.<my domain>',
  context: 'cert_issue',
  subject: '<my domain>',
  altnames: [ '<my domain>' ],
  toJSON: [Function: errorToJSON],
  _site: {
    subject: '<my domain>',
    altnames: [ '<my domain>' ],
    renewAt: 1
  }
}
Error: queryTxt ENOTFOUND _acme-challenge.<my domain>
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryTxt',
  hostname: '_acme-challenge.<my domain>'
}
Waiting for 10000 ms before attempting propagation verification retry 1 / 30.
Error: queryTxt ENOTFOUND _greenlock-dryrun-16ba4f41.<my domain>
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryTxt',
  hostname: '_greenlock-dryrun-16ba4f41.<my domain>'
}
Waiting for 10000 ms before attempting propagation verification retry 2 / 30.
```

and this continues like this until it eventually stops by itself, but without any certificate generated for my domain.

I'm not sure wether I'm doing something wrong or not, I'm posting the issue here since I don't have any greenlock log after your module's one, feel free to correct me if I'm wrong!

Thanks in advance for the help :)

**Comment by Cherry** [comment]
It sounds like you're just running into limitations of DNS unfortunately. With DNS caches everywhere, it's extremely common that the records added for verification won't propagate in time for the plugin top be happy.

There's very little that we can really do to "fix" this, but a few things I'd recommend to give you the best chance of success:

1) Set your local DNS to use a service that isn't so heavy-handed on caching. If you're using the DNS provided by your ISP, this almost certainly won't have the newly updated records very quickly. Cloudflare's [`1.1.1.1`](https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/) public DNS is a good one to use.

2) Make sure you have  `verifyPropagation` set on this module - it looks like you do from the logs. You can try playing with the `waitFor` and `retries` options too - setting these higher may help. `waitFor` defaults to `10000` (10 seconds), and `retries` defaults to 30. 

3) Make sure you don't have a local DNS cache service. Depending on where you're running this, some flavours of linux use `systemd-resolve` to cache DNS records by default, which can improve performance, but on frequent changing records like for ACME verification, it can cause problems.

**Comment by Unyxos** [comment]
Hello! Thanks for the very fast response :)

I was already using 1.1.1.1 as dns and cleared the cache... however changing the `waitFor` to 20000 seems to have helped, it now generates certificates.

It's now working ! Thanks :)
