### ISSUE TITLE
API Token requires access to all zones on account

### ISSUE THREAD

**Issue by kentonv** [nodecraft/acme-dns-01-cloudflare#8]
The readme says to give tokens the permission "Account -> Account Settings: Read" in order to get `com.cloudflare.api.account.zone.list` to be able to list zones. It turns out that this permission was never meant to be granted this way, and Cloudflare recently "fixed" the "bug" on their end, so this no longer works.

Now, in order to list zones, the token must be granted permission to all zones on the account under "zone resources". Unfortunately, there's no way to grant read access to all zones while granting DNS write to only a specific zone, so in order to use acme-dns-01-cloudflare, it is now necessary to grant DNS write access to all zones on my account, even if I only really want to issue certificates under one specific zone.

Perhaps the module could add a config option to specify zone names, so that it doesn't need to try to list them via the API?

_(Note: I work for Cloudflare, but I am currently here because I'm trying to add Let's Encrypt support to Sandstorm.io, which is unrelated to my work at Cloudflare.)_

**Comment by Cherry** [comment]
Hi Kenton, thanks so much for the info!

I actually noticed this myself on Friday when trying to generate a certificate but didn't get around to creating an issue or solution yet.

What do you think of something like this, which would allow users to pass in a zone map of domain => zone ID?
```js
const cloudflareDns01 = new acmeDnsCloudflare({
	token: 'xxxxxx',
	verifyPropagation: true,
	verbose: true,
	zones: {
		"example.com": "asdfgh",
		"example2.com": "zxcvbn"
	}
});
```

The module could then first check the `zones` configuration as passed in, but fallback to querying Cloudflare's API for the zones if it needs to.

As a side note, allowing `com.cloudflare.api.account.zone.list` as a separate explicitly granted permission would be really awesome. 😉

**Comment by kentonv** [comment]
Oh geez... The API doesn't provide any way to map a zone name to an ID without listing zones?

(Yeah this is not my department at Cloudflare. :sweat_smile:)

**Comment by Cherry** [comment]
As far as I can tell looking at https://api.cloudflare.com/#zone-list-zones, there's a filter `name` for the `GET zones` call, but no way to specify multiple filters. So if you wanted to create certs for 30 zones on your account, this would be 30 separate API calls vs 1 or 2 for a generic `GET zones` listing.

But, that's assuming the `GET zones` call would take into account permissions on specific zones, and with some quick testing, it doesn't seem to. Even if I explictly do `GET zones?name=example.com` where `example.com` is a zone I have access to, I still receive the `com.cloudflare.api.account.zone.list` permission error.

Unless I'm missing an available API call on Cloudflare's end, the only 2 solutions here (when using an api token) are passing in the zone names/IDs map, or giving your API token access to all zones are on the account, neither of which are ideal. 😕

**Comment by kentonv** [comment]
Ugh, lame. Let me poke some people internally about this.

Though I guess this is still much better than the pre-api-token world...

**Comment by Cherry** [comment]
Yeah, a revocable token is still way better than a global API key, even if you have to give it more permissions than really intended. 😀

I'll see about updating the README here shortly with the new permission information. Hopefully we can find a better solution soon!

**Comment by kentonv** [comment]
I checked internally and it seems like there is a desire to fix this, but it's not as easy as it looks, so probably shouldn't expect it to change in the near term.

I guess having some way to specify zone tags manually might be neat though I expect most people won't want to do the work of looking them all up.

**Comment by Cherry** [comment]
Thanks for the update. I'll think about this a little and see what I want to do. Specifying a `zones` map could be a nice interim feature, and just fallback to using the API for those who don't wish to configure this, or for missing zones, with hopefully a better solution coming in the future.

**Comment by Cherry** [comment]
Good news! With changes to Cloudflare's new zone-scoped roles, this no longer seems to be an issue. A "zone list" request now returns just the zones an account has access to. 🥳
